
version: '2.1'
services:
  base-elasticsearch2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_IMAGE_TAG=${IMAGE_ARG_IMAGE_TAG:-2.4.4}
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-elasticsearch2}:${IMAGE_TAG:-2.4.4}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.elasticsearch2}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/elasticsearch2/standalone}
    restart: always
