
version: '2.1'
services:
  elasticsearch2-develop:
    extends:
      file: docker-compose-base.yml
      service: base-elasticsearch2
    container_name: ${CONTAINER_HOST_NAME:-elasticsearch2}
    hostname: ${CONTAINER_HOST_NAME:-elasticsearch2}
    ports:
    - "${ELASTICSEARCH_9200_PORT:-9200}:9200"
    - "${ELASTICSEARCH_9300_PORT:-9300}:9300"
    networks:
      local-network:
        ipv4_address: 172.16.238.24
        #ipv6_address: 2001:3984:3989::24
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - data:/usr/share/elasticsearch/data

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
