
version: '2.1'
services:
  elasticsearch2:
    extends:
      file: docker-compose-base.yml
      service: base-elasticsearch2
    container_name: ${CONTAINER_HOST_NAME:-elasticsearch2}
    hostname: ${CONTAINER_HOST_NAME:-elasticsearch2}
    network_mode: bridge
    ports:
    - "${ELASTICSEARCH_9200_PORT:-9200}:9200"
    - "${ELASTICSEARCH_9300_PORT:-9300}:9300"
    volumes:
    - data:/usr/share/elasticsearch/data

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
