
version: '2.1'
services:
  elasticsearch2:
    extends:
      file: docker-compose-base.yml
      service: base-elasticsearch2
    container_name: ${CONTAINER_HOST_NAME:-standalone.elasticsearch2}
    hostname: ${CONTAINER_HOST_NAME:-standalone.elasticsearch2}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.elasticsearch2}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/elasticsearch2/standalone}
    network_mode: bridge
    ports:
    - "${EXTERNAL_ELASTICSEARCH_9200_PORT:-9200}:9200"
    - "${EXTERNAL_ELASTICSEARCH_9300_PORT:-9300}:9300"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - data:/usr/share/elasticsearch/data

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
